// src/components/App/App.vue
<template>
    <div>
        <h1 class="app-header">Hello World!</h1>
        <p v-if="isNetworkRunning">Network connected!</p>
        <p v-else>Network not connected!</p>
    </div>
</template>

<script>
    import Ballot from '../../contracts/Ballot.sol';

    export default {
        name: 'App',
        props: {
            isNetworkRunning: { // TODO: handle no Ethereum network running.
                type: Boolean,
                default: false
            }
        },
        data: function () {
            return {
                metaCoinContract: null
            };
        },

        // Life cycle methods.
        mounted: function () {
            if (this.isNetworkRunning) {
                // this.metaCoinContract = Voting;
                //
                // this.metaCoinContract.setProvider(window.web3.currentProvider);
                //
                // console.log(Voting);
            }
        }
    };
</script>

<style lang="scss" scoped>
    .app {
        &-header {
             color: red;
         }
    }
</style>

// src/components/App/App.jsx
import PropTypes from 'prop-types';
import React, { Component } from 'react';
//import { default as contract } from 'truffle-contract';

// Styles.
import './styles.scss';

// Artifacts.
import ballotArtifacts from '../../../build/contracts/Ballot.json';

export default class App extends Component {
    static defaultProps = {
        isNetworkRunning: false
    };
    static propTypes = {
        isNetworkRunning: PropTypes.bool
    };

    constructor() {
        super();

        this.ballotContract = null;

        console.log(ballotArtifacts);
    }

    render() {
        return (
            <div>
                <h1 className="app-header">Hello World!</h1>
                <p>{ (this.props.isNetworkRunning ? 'Network connected!': 'Network not connected!') }</p>
            </div>
        );
    }
}
